version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: laravel-avanzado-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker:/var/www/html/docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    networks:
      - laravel-avanzado-net
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-avanzado-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:delegated
    networks:
      - laravel-avanzado-net
    command: php-fpm
    # command: >
    #   sh -c "[ ! -d 'vendor' ] && composer install --optimize-autoloader --no-dev; php artisan key:generate && php artisan optimize:clear && php-fpm"
  node:
    image: node:22.0.0
    container_name: laravel-avanzado-node
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:delegated
    ports:
      - "5173:5173"
    command: tail -f /dev/null
    # command: >
    #   sh -c "[ ! -d 'node_modules' ] && npm install; npm run dev"
    networks:
      - laravel-avanzado-net
    depends_on:
      - php

networks:
  laravel-avanzado-net:
    driver: bridge
